# Generated by Django 4.1.7 on 2023-03-05 11:28

from django.db import migrations, models
import pi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PiDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "remote_last_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=pi.models.image_path
                    ),
                ),
                ("remote_last_image_updated", models.DateTimeField(null=True)),
                ("socket_status_updated", models.DateTimeField(null=True)),
                (
                    "cec_hdmi_status",
                    models.CharField(default="unknown", max_length=100),
                ),
                (
                    "group_channel_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
