# Generated by Django 4.0 on 2023-03-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidevice',
            name='tv_display_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
