# Generated by Django 4.0 on 2023-03-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0002_pidevice_tv_display_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pidevice',
            name='remote_last_image_updated',
        ),
    ]
