# Generated by Django 4.0 on 2023-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0003_remove_pidevice_remote_last_image_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketDeviceIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('connections_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
